export default [
    {
        text:"环境搭建",
        link:"/guide/front-end/typescript/环境搭建"
    },
    {
        text:"原始类型",
        link:"/guide/front-end/typescript/原始类型"
    },
    {
        text:"数组类型",
        link:"/guide/front-end/typescript/数组类型"
    },
    {
        text:"联合与交叉类型",
        link:"/guide/front-end/typescript/联合与交叉类型"
    },
    {
        text:"any与unknown",
        link:"/guide/front-end/typescript/any与unknown"
    },
    {
        text:"接口",
        link:"/guide/front-end/typescript/接口"
    },
    {
        text:"类型别名",
        link:"/guide/front-end/typescript/类型别名"
    },
    {
        text:"函数类型",
        link:"/guide/front-end/typescript/函数类型"
    },
    {
        text:"promise",
        link:"/guide/front-end/typescript/promise"
    },
    {
        text:"泛型",
        link:"/guide/front-end/typescript/泛型"
    },
    {
        text:"类",
        link:"/guide/front-end/typescript/类"
    },
    {
        text:"工具类型",
        link:"/guide/front-end/typescript/工具类型"
    },
]