export default [
  {
    text:"介绍",
    link:"/guide/Framework/weapp/介绍"
},
{
    text:"数据绑定",
    link:"/guide/Framework/weapp/数据绑定"
},
{
    text:"事件系统",
    link:"/guide/Framework/weapp/事件系统"
},
{
    text:"双向数据绑定",
    link:"/guide/Framework/weapp/双向数据绑定"
},
{
    text:"数组渲染",
    link:"/guide/Framework/weapp/数组渲染"
},
{
    text:"条件渲染",
    link:"/guide/Framework/weapp/条件渲染"
},
{
    text:"WXS脚本",
    link:"/guide/Framework/weapp/WXS脚本"
},
{
    text:"生命周期",
    link:"/guide/Framework/weapp/生命周期"
},
{
    text:"全局变量",
    link:"/guide/Framework/weapp/全局变量"
},
{
    text:"路由导航",
    link:"/guide/Framework/weapp/路由导航"
},
{
    text:"自定义组件",
    link:"/guide/Framework/weapp/自定义组件"
},
{
    text:"父子组件通信",
    link:"/guide/Framework/weapp/父子组件通信"
},
{
    text:"数据请求",
    link:"/guide/Framework/weapp/数据请求"
},
{
    text:"云开发",
    link:"/guide/Framework/weapp/云开发"
},
];
