export default [
    {
        text:"环境搭建",
        link:"/TypeScript/环境搭建"
    },
    {
        text:"原始类型",
        link:"/TypeScript/原始类型"
    },
    {
        text:"数组类型",
        link:"/TypeScript/数组类型"
    },
    {
        text:"联合与交叉类型",
        link:"/TypeScript/联合与交叉类型"
    },
    {
        text:"any与unknown",
        link:"/TypeScript/any与unknown"
    },
    {
        text:"接口",
        link:"/TypeScript/接口"
    },
    {
        text:"类型别名",
        link:"/TypeScript/类型别名"
    },
    {
        text:"函数类型",
        link:"/TypeScript/函数类型"
    },
    {
        text:"promise",
        link:"/TypeScript/promise"
    },
    {
        text:"泛型",
        link:"/TypeScript/泛型"
    },
    {
        text:"类",
        link:"/TypeScript/类"
    },
    {
        text:"工具类型",
        link:"/TypeScript/工具类型"
    },
]