export default [
	{
		text: "前置知识",
		collapsed: true,
		items: [
			{ text: "常用浏览器以及内核", link: "/guide/html/浏览器" },
			{ text: "Web标准与组成", link: "/guide/html/web标准" },
			{ text: "标签", link: "/guide/html/标签" },
			{ text: "HTML文档骨架", link: "/guide/html/html文档骨架" },
			{ text: "路径", link: "/guide/html/路径" },
		],
	},
	{
		text: "HTML基础",
		collapsed: true,
		items: [
			{ text: "注释标签", link: "/guide/html/注释" },
			{ text: "排版标签", link: "/guide/html/排版标签" },
			{ text: "文本格式化标签", link: "/guide/html/文本格式化标签" },
			{ text: "容器标签", link: "/guide/html/容器标签" },
			{ text: "图像标签", link: "/guide/html/图像标签" },
			{ text: "超链接标签", link: "/guide/html/超链接" },
			{ text: "表格标签", link: "/guide/html/表格标签" },
			{ text: "列表标签", link: "/guide/html/列表标签" },
			{ text: "表单标签", link: "/guide/html/表单标签" },
			{ text: "特殊字符", link: "/guide/html/字符实体" },
		],
	},
	{
		text: "HTML5",
		collapsed: true,
		items: [
			{ text: "语义化标签", link: "/guide/html/语义化标签" },
			{ text: "多媒体标签", link: "/guide/html/多媒体标签" },
			{ text: "表单元素", link: "/guide/html/表单元素" },
			{ text: "canvas", link: "/guide/html/canvas" },
			{ text: "svg", link: "/guide/html/svg" },
			{ text: "地理定位", link: "/guide/html/地理定位" },
			{ text: "拖放", link: "/guide/html/拖放" },
			{ text: "Web存储", link: "/guide/html/本地存储" },
			{ text: "应用缓存", link: "/guide/html/应用缓存" },
			{ text: "Web Worker", link: "/guide/html/webworker" },
		],
	},
]
